spring.application.name=Dashboard-foot

# Football Data API Configuration
football-data.api.base-url=https://api.football-data.org/v4
football-data.api.token=1f1511998298477691a3fa4ddf266f1e

# Server port
server.port=8080

# Cache Configuration (Caffeine) - 1 minute pour respecter la limite de 10 req/min
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=60s
spring.cache.type=caffeine
